# Generated by Django 5.2.7 on 2025-10-22 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('margen_ganancia_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Margen de ganancia sugerido para esta categoría. Ej: 30.5 para 30.5%', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recargo_credito_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de recargo para pagos con tarjeta de crédito. Ej: 10.5', max_digits=5)),
                ('descuento_efectivo_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento para pagos en efectivo. Ej: 5.0', max_digits=5)),
                ('recargo_qr_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de recargo para pagos con QR. Ej: 6.0', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('frecuencia_reparto_dias', models.PositiveIntegerField(blank=True, help_text='¿Cada cuántos días pasa el proveedor? Ej: 7 (semanal), 15 (quincenal)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_barras', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_minimo', models.PositiveIntegerField(default=5, help_text='El sistema alertará cuando el stock total sea inferior a este número.')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(choices=[('gondola', 'Góndola'), ('deposito', 'Depósito')], default='deposito', max_length=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilusuario', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece este usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_recargo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('qr', 'QR')], default='efectivo', max_length=10)),
                ('cuotas', models.PositiveIntegerField(default=1, help_text='Número de cuotas si el pago es con crédito')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.venta')),
            ],
        ),
    ]
