# Generated by Django 5.2.7 on 2025-10-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='frecuencia_reparto_dias',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dia_semana_reparto',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana principal en que entrega.', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='frecuencia_reparto',
            field=models.IntegerField(blank=True, choices=[(7, 'Semanal'), (14, 'Quincenal'), (30, 'Mensual')], help_text='Cada cuántos días entrega (aprox).', null=True),
        ),
    ]
