# Generated by Django 5.2.7 on 2025-11-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_proveedor_frecuencia_reparto_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_perecedero',
            field=models.BooleanField(default=True, help_text='Marcar si este producto tiene fecha de vencimiento. (Ej: Bebidas, Golosinas). Desmarcar para (Ej: Encendedores, Vasos).'),
        ),
    ]
