# Generated by Django 5.2.7 on 2025-11-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_es_perecedero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_favorito',
            field=models.BooleanField(default=False, help_text='Marcar para que aparezca en la grilla de Venta Rápida'),
        ),
    ]
