# Generated by Django 5.2.7 on 2025-11-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_es_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvaseRetornable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor_deposito', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockEnvases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vacia', models.PositiveIntegerField(default=0)),
                ('envase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.envaseretornable')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
            options={
                'unique_together': {('envase', 'sucursal')},
            },
        ),
    ]
