# Generated by Django 5.2.7 on 2025-11-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_alter_venta_metodo_pago_venta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo deudor con este proveedor (positivo = vos debés, negativo = tenés crédito)', max_digits=10),
        ),
    ]
