# Generated by Django 5.2.7 on 2025-11-11 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facturaproveedor_pagoproveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_turno', models.DateTimeField()),
                ('fecha_cierre_turno', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas_qr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cobros_fiado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagos_proveedor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_en_caja_declarado', models.DecimalField(decimal_places=2, help_text='El monto que el empleado contó físicamente en la caja', max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('usuario_cierre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
