# Generated by Django 5.2.7 on 2026-02-08 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_prediccionventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEscaneo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ultimo_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_procesado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
