# Generated by Django 5.2.7 on 2026-02-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sesionescaneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracionm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Mi Kiosco', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='limite_credito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_actual',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuenta_corriente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Cliente Genérico', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
