# Generated by Django 5.2.7 on 2026-02-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configuracionm_remove_cliente_limite_credito_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracionm',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre_negocio',
            field=models.CharField(default='Mi Kiosco', help_text='Nombre que se verá en el menú principal y tickets.', max_length=100),
        ),
    ]
